#coding:utf-8

#relation dict

#excel to mysql
relation_dict_o32_trade={'trade_date':'发生日期','fund_id':'账户编号','fund_name':'账户名称','sec_id':'证券代码','sec_name':'证券名称',
               'trade_direct':'委托方向','trade_volume':'成交数量','trade_amount':'发生金额(全价)'}

relation_dict_sjsjg={
'JGJSZH':'JGJSZH','JGBFZH':'JGBFZH','JGSJLX':'JGSJLX','JGYWLB':'JGYWLB','JGZQDM':'JGZQDM',
'JGJYDY':'JGJYDY','JGZQZH':'JGZQZH','JGCJSL':'JGCJSL','JGQSSL':'JGQSSL','JGJSSL':'JGJSSL',
'JGCJJG':'JGCJJG','JGQSJG':'JGQSJG','JGZQLB':'JGZQLB','JGQSBJ':'JGQSBJ','JGYHS':'JGYHS',
'JGJYJSF':'JGJYJSF','JGJGGF':'JGJGGF','JGGHF':'JGGHF','JGJSF':'JGJSF','JGSXF':'JGSXF','JGQSYJ':'JGQSYJ',
'JGQTFY':'JGQTFY','JGZJJE':'JGZJJE','JGSFJE':'JGSFJE','JGJSBZ':'JGJSBZ','JGZYDH':'JGZYDH',
'JGCJRQ':'JGCJRQ','JGQSRQ':'JGQSRQ','JGJSRQ':'JGJSRQ','JGFSRQ':'JGFSRQ','JGQTRQ':'JGQTRQ',
'JGJYFS':'JGJYFS'
}

jsmx_li=['SCDM','JLLX','JYFS','JSFS','YWLX','QSBZ','GHLX','JSBH',
'CJBH','SQBH','WTBH','JYRQ','QSRQ','JSRQ','QTRQ','WTSJ','CJSJ',
'XWH1','XWH2','XWHY','JSHY','TGHY','ZQZH','ZQDM1','ZQDM2','ZQLB',
'LTLX','QYLB','GPNF','MMBZ','SL','CJSL','ZJZH','BZ','JG1','JG2',
'QSJE','YHS','JSF','GHF','ZGF','SXF','QTJE1','QTJE2','QTJE3','SJSF',
'JGDM','FJSM',
]

sjsmx_li=[
'MXJSZH','MXBFZH','MXSJLX','MXYWLB','MXZQDM','MXJYDY','MXTGDY','MXZQZH',
'MXDDBH','MXYYB','MXZXBH','MXYWLSH','MXCJSL','MXQSSL',
'MXCJJG','MXQSJG','MXXYJY','MXPCBS','MXZQLB','MXZQZL','MXGFXZ','MXJSFS',
'MXHBDH','MXQSBJ','MXYHS','MXJYJSF','MXJGGF','MXGHF','MXJSF','MXSXF',
'MXQSYJ','MXQTFY','MXZJJE','MXSFJE','MXCJRQ','MXQSRQ','MXJSRQ','MXFSRQ',
'MXQTRQ','MXSCDM','MXJYFS','MXZQDM2','MXTGDY2','MXDDBH2','MXCWDH','MXPPHM',
'MXFJSM','MXBYBZ',
]

tgdxw_li=['L_ZTBH','L_LB','VC_CODE','L_SCLB'
]

tfundinfo_li=['L_FUNDID','VC_CODE','VC_NAME','VC_TGR']

